routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
})->middleware('guest');

Route::group(['middleware'=>'auth','role'=>['admin','qacoordinator','qualityassurancemanager']], function() {
    Route::resource('admin/', 'AdminHomeController');
    Route::resource('admin/posts', 'PostController');
});

Route::group(['middleware'=>'auth','role'=>['qualityassurancemanager']], function() {
    Route::resource('admin/tags', 'TagController');
});

Route::group(['middleware'=>'auth','role'=>['admin']], function(){
    Route::resource('admin/roles', 'RoleController');
    Route::resource('admin/departments', 'DepartmentController');
    Route::resource('admin/users', 'UserController');
    Route::resource('admin/session-departments', 'SessionDepartmentController');
    Route::resource('admin/batches', 'BatchController');
    Route::resource('admin/sections', 'SectionController');
});


Route::get('/getDeptWiseSession',['uses'=>'SessionDepartmentController@getDeptWiseSession','role'=>'admin','as'=>'getDeptWiseSession']);
Route::post('/getsessiondata',['uses'=>'SessionDepartmentController@getsessiondata','role'=>'qacoordinator','as'=>'getsessiondata']);
Route::post('/manageideapost',['uses'=>'SessionDepartmentController@manageideapost','role'=>'qacoordinator','as'=>'manageideapost']);
Route::post('/newPErmitForIdea',['uses'=>'SessionDepartmentController@newPErmitForIdea','role'=>'qacoordinator','as'=>'newPErmitForIdea']);
Route::post('/existingDate',['uses'=>'SessionDepartmentController@existingDate','role'=>'qacoordinator','as'=>'existingDate']);
Route::post('/disableIdeaControl',['uses'=>'SessionDepartmentController@disableIdeaControl','role'=>'qacoordinator','as'=>'disableIdeaControl']);
Route::get('/manageideapostPermission',['uses'=>'SessionDepartmentController@manageideapostPermission','role'=>'qacoordinator','as'=>'manageideapostPermission']);
Route::get('/getSessionWiseBatch',['uses'=>'BatchController@getSessionWiseBatch','role'=>'admin','as'=>'getSessionWiseBatch']);
Route::get('/allstudents',['uses'=>'Student\StudentController@allstudents','role'=>'admin','as'=>'allstudents']);
Route::get('/deptwiseallstudents',['uses'=>'Student\StudentController@deptwiseallstudents','role'=>'qacoordinator','as'=>'deptwiseallstudents']);
Route::get('/enable-post-idea',['uses'=>'Idea\IdeaController@enableidea','role'=>'qacoordinator','as'=>'enable-post-idea']);
Route::get('/alldocs',['uses'=>'Idea\IdeaController@alldocs','role'=>'qualityassurancemanager','as'=>'alldocs']);
Route::get('/approvenewidea',['uses'=>'Idea\IdeaController@approvenewidea','role'=>'qacoordinator','as'=>'approvenewidea']);
Route::get('/newidea',['uses'=>'Idea\IdeaController@newidea','role'=>'qacoordinator','as'=>'newidea']);
Route::post('/approve',['uses'=>'Idea\IdeaController@approve','role'=>'qacoordinator','as'=>'approve']);
Route::post('/deletePost',['uses'=>'Idea\IdeaController@deletePost','role'=>'qacoordinator','as'=>'deletePost']);
Route::post('/getuserinfo',['uses'=>'Idea\IdeaController@getuserinfo','role'=>'qacoordinator','as'=>'getuserinfo']);
Route::get('/allnewPosts',['uses'=>'Idea\IdeaController@allnewPosts','role'=>'qacoordinator','as'=>'allnewPosts']);
Route::get('/no_idea_comments',['uses'=>'Idea\IdeaController@no_idea_comments','role'=>['qacoordinator','qualityassurancemanager'],'as'=>'no_idea_comments']);
Route::get('/individualIdeaWithNoComment/{id}',['uses'=>'Idea\IdeaController@individualIdeaWithNoComment','role'=>['qacoordinator','qualityassurancemanager'],'as'=>'individualIdeaWithNoComment']);
Route::get('/annomynousIdeaAndComment',['uses'=>'Idea\IdeaController@annomynousIdeaAndComment','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'annomynousIdeaAndComment']);
Route::get('/categorywiseidea',['uses'=>'Idea\IdeaController@categorywiseidea','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'categorywiseidea']);
Route::post('/getallideaByTag',['uses'=>'Idea\IdeaController@getallideaByTag','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'getallideaByTag']);
Route::get('/chart',['uses'=>'AdminHomeController@chart','as'=>'chart','role'=>'admin']);
Route::get('/total_post_by_each_dept',['uses'=>'AdminHomeController@total_post_by_each_dept','as'=>'total_post_by_each_dept','role'=>['admin','qualityassurancemanager']]);



Auth::routes();
Route::get('/profile',['uses'=>'HomeController@profile','as'=>'profile','role'=>['student']]);

Route::get('/', ['uses'=>'HomeController@index','as'=>'home','role'=>['student']]);

Route::get('/post', ['uses'=>'HomeController@createPost','as'=>'createPost','role'=>['student']]);

Route::post('/post', ['uses'=>'HomeController@postIdea','as'=>'post','role'=>['student']]);

Route::get('/post/show/{id}', ['uses'=>'HomeController@postDetails','as'=>'post-details','role'=>['student']]);


Route::post('/comment', ['uses'=>'HomeController@postComment','as'=>'comment','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);

Route::post('/postLike', ['uses'=>'HomeController@postLike','as'=>'postLike','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);

Route::post('/postView', ['uses'=>'HomeController@postView','as'=>'postView','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);


Route::post('/getallFile',['uses'=>'Idea\IdeaController@getallFile','role'=>'qualityassurancemanager','as'=>'getallFile']);
Route::get('/myidea',['uses'=>'Idea\IdeaController@myidea','role'=>'student','as'=>'myidea']);
Route::post('/myidea',['uses'=>'Idea\IdeaController@deleteIdea','role'=>'student','as'=>'deleteIdea']);
Route::get('/myidea/{id}/edit',['uses'=>'Idea\IdeaController@editMyIdea','role'=>'student','as'=>'editmyidea']);
Route::post('/myidea/{post}',['uses'=>'Idea\IdeaController@updateIdea','role'=>'student','as'=>'updatemyidea']);

resources/views/404.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>404 | Not found</title>
</head>
<body>

<h2 style="color: #ef3232;">404 | Sorry, Nothing to serve !!</h2>

</body>
</html>

resources/views/admin_mail.blade.php
<h4>{{$name}} posted a new idea</h4>

resources/views/comment_mail.blade.php
<h4>{{$name}} commented  on your post :  {{$comment}}</h4>

resources/views/myidea.blade.php
@extends('layouts.app')

@section('style')
<link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
<style type="text/css">

    input.rounded {
        margin-right: 10px;
        border: 1px solid #ccc;
        -moz-border-radius: 20px;
        -webkit-border-radius: 20px;
        border-radius: 20px;
        -moz-box-shadow: 2px 2px 3px #666;
        -webkit-box-shadow: 2px 2px 3px #666;
        box-shadow: 2px 2px 3px #666;
        font-size: 18px;
        padding: 4px 7px;
        outline: 0;
        -webkit-appearance: none;
    }

    .glyphicon.glyphicon-comment{
        font-size: 25px;
    }
    a:link {
        text-decoration: none;
    }
    a:hover {
        text-decoration: none;
    }
    p{
        font-size: 14px;
        font-family: 'Slabo 27px', serif;
    }

    #idea{
        font-weight:bold;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            @if(session('delete'))
            <div class="alert alert-info">
                {{session('delete')}}
            </div>
            @endif

            @if($d!=null)
            <div class="panel panel-primary">
                <div class="panel-heading">
                    All the idea you have posted !!
                    <div class="clearfix"></div>
                </div>

                <div class="panel-body">
                    @foreach ($d as $post)
                    <div class="modal-dialog modal-lg" role="document">

                        <div class="modal-content">

                            <div class="modal-header">
                                <div class="pull-right">
                                    <button class="btn btn-default deletebutton" style="background-color: #f7091d;color:#fff" title="Remove post" data-toggle="modal" data-target="#myModal" data-id="{{$post->id}}"><i class="fa fa-minus-circle" aria-hidden="true"></i></button>
                                   
                                    <a style="background-color: #006622;color:#fff" type="button" href="{{ route('editmyidea', ['post' => $post->id]) }}" class="btn btn-default fa fa-pencil" title="Edit post"></a>
                                </div>
                                {{--<h2 class="modal-title"><a href="{{ route('post-details', ['id' => $post->id]) }}">{{ $post->title }}</a></h2>--}}
                                <p class="lead">

                                    {{$post->user->name}}

                                </p>
                                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ $post->created_at->diffForHumans() }}
                                </p>
                            </div>
                            <div class="modal-body">
                                <p id="idea"><i class="fa fa-lightbulb-o" aria-hidden="true" style="color: #fc5507;font-size: 30px"></i> {{ $post->body }}</p>
                                <a href="javascript:void(0)" data-toggle="collapse" data-target="#comments_{{ $post->id }}"><b>See all comments</b></a>
                            </div>
                            <div class="modal-footer">
                                <a type="button" style="cursor: pointer" class="glyphicon glyphicon-comment" title="Leave a Comments" data-toggle="collapse" data-target="#comments_{{ $post->id }}" aria-expanded="false" aria-controls="comments_{{ $post->id }}"></a>
                                <div class="collapse" id="comments_{{ $post->id }}">
                                    <div class="well well-sm pull-left">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <form class="form-inline" method="post" action="{{ url('comment') }}">
                                                    {{ csrf_field() }}
                                                    <input type="hidden" name="post_id" value="{{ $post->id }}">
                                                    <input type="hidden" name="user_id" value="{{ Auth::user()->id}}">
                                                    <div class="form-group">
                                                        <input size="60" name="comment" class="form-control rounded" type="text" placeholder=" Write a comment......">
                                                    </div>
                                                    <div style="margin-right: 10px;" class="checkbox">
                                                        <label>
                                                            <input type="checkbox" name="anonymous" value="0"> Hide profile
                                                            {{--<input type="hidden" name="anonymous" value="0">--}}
                                                        </label>
                                                    </div>
                                                    <button type="submit" class="btn btn-primary ">Comment</button>
                                                </form><hr>
                                                <!-- Comment -->
                                                @foreach ($post->comment as $comment)
                                                @if($comment->user->role->role_name=='student')
                                                <div class="media">
                                                    <a class="pull-left" href="#">
                                                        @if ($comment->anonymous == 1)
                                                        <img class="media-object" src="{{asset('uploads/users/'.$post->user->image)}}" alt="" height="30px" width="30px">
                                                        @else
                                                        <img class="media-object" src="{{asset('image/anon.png')}}" alt="" height="30px" width="30px">
                                                        @endif
                                                    </a>
                                                    <div class="media-body">
                                                        <p style="text-align: left;">

                                                            @if ($comment->anonymous == 1)
                                                            Comment by {{$comment->user->name}}
                                                            @else
                                                            Comment by <i class="fa fa-user-secret" aria-hidden="true" style="color: #ff3838;"></i> Anonymous
                                                            @endif
                                                            <small>{{$comment->created_at->diffForHumans()}}</small><br>
                                                            <i class="fa fa-comments" aria-hidden="true" style="color: #56ccff"></i> {{ $comment->comment}}
                                                        </p>
                                                        @endif
                                                        {{--@endif--}}
                                                        {{--</p>--}}

                                                    </div>
                                                </div>
                                                @endforeach
                                            </div>
                                        </div>
                                        <hr>
                                    </div>

                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->

                    @endforeach

                    {{$d->links()}}
                </div>
            </div>
            @endif

        </div>
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-body">
                <strong><p>Edit your post </p></strong>
            </div>
            <div class="modal-footer">
                <form action="{{route('deleteIdea')}}" method="post">
                    {{csrf_field()}}
                    <input type="hidden" name="idea_id" id="idea_id">
                    <button type="submit" class="btn btn-default" style="background-color: #ff2323;color: #fff;">Yes</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                </form>
            </div>

        </div>

    </div>
</div>

    @endsection

    @section('script')

    <script>
        $(document).on('click','.deletebutton',function () {
            $('#idea_id').val($(this).data('id'));

        });

        {{--$('#deleteButton').on('click', deleteSection);--}}

        {{--function deleteSection() {--}}
            {{--var deleteableSectionId =  $('#idea_id').val();--}}
            {{--var deleteUrl = '{{ route('sections.destroy', ['section' => ':sectionId']) }}';--}}
            {{--deleteUrl = deleteUrl.replace(':sectionId', deleteableSectionId);--}}

            {{--$.ajax({--}}
                {{--url : deleteUrl,--}}
                {{--type : 'POST',--}}
                {{--data : {--}}
                    {{--"_token": '{{ csrf_token() }}',--}}
                    {{--"_method": 'DELETE',--}}
                    {{--id:deleteableSectionId--}}
                {{--},--}}
                {{--success: function(result) {--}}
                    {{--loadSection();--}}
                    {{--$('#deleteConfirmationModel').modal('hide');--}}
                {{--}--}}
            {{--});--}}
        {{--}--}}
    </script>
    @endsection

resources/views/post-details.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Post Details</div>

                <div class="panel-body">
        
                
                        <h2>
                            <a href="#">{{ $post->title }}</a>
                        </h2>
                        <p class="lead">
                            by <a href="index.php">{{ $post->user->name }}</a>
                        </p>
                        <p><span class="glyphicon glyphicon-time"></span> Posted on {{ $post->created_at }}</p>
                        <hr>
                        <p>{{ $post->body }}</p>
                        

                        <hr>
                
     
 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Post</div>
                <div class="panel-body">
                        <form method="post" action="{{ route('updatemyidea',['post' => $post->id]) }}" enctype="multipart/form-data">

                        {{ csrf_field() }}
                         {{-- {{ method_field('PATCH') }} --}}
                          <input type="hidden" name="user_id" id="user_id" class="form-control" value="{{ Auth::user()->id }}">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="tag_id">Tag Name</label>
                              <select class="form-control tag_id" name="tag_id" id="tag_id">
                                <option value="{{ $post->tag_id }}">{{ $post->tag->name }}</option>
                                @foreach ($tags as $tag)
                                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                                </select>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <label for="post_date">Date</label>
                            <div class="form-group">
                              <input type="date" name="post_date" id="post_date" class="form-control" value="{{ $post->created_at->format('Y-m-d') }}" required>
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="title">Title</label>
                              <input type="text" name="title" id="title" class="form-control" value="{{ $post->title }}">
                            </div>
                          </div>
                          <div class="col-md-12">
                            <label for="body">Your Idea</label>
                            <div class="form-group">
                              <textarea type="text" class="form-control" name="body">{{ $post->body }}</textarea>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <label>Document</label>
                            <div class="form-group">
                              <input type="file" name="doc">
                              @if($post->document)
                              <label>Uploaded File: {{ $post->document->doc }}</label>
                              @endif
                            </div>
                        </div>
                          <div class="col-md-6">
                            <label>Privacy</label>
                            <div class="checkbox">
                              <label><input type="checkbox" value="0" name="profile_privacy"> Yes</label>
                              <label><input type="checkbox" value="1" name="profile_privacy"> No</label>
                            </div>
                          </div>

                        </div>


                         <button type="submit" class="btn btn-primary"> <i class="glyphicon glyphicon-ok"> </i>  Update</button>

                        <a type="button" href="{{ route('myidea') }}" class="btn btn-danger"> <i class="glyphicon glyphicon-remove"> </i> Cancel</a>



                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

{{-- @section('script')
  <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>
  <script>CKEDITOR.replace( 'body' );</script>
@endsection --}}

resources/views/profile.blade.php
@extends('layouts.app')

@section('style')
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <style type="text/css">

        input.rounded {
            margin-right: 10px;
            border: 1px solid #ccc;
            -moz-border-radius: 20px;
            -webkit-border-radius: 20px;
            border-radius: 20px;
            -moz-box-shadow: 2px 2px 3px #666;
            -webkit-box-shadow: 2px 2px 3px #666;
            box-shadow: 2px 2px 3px #666;
            font-size: 18px;
            padding: 4px 7px;
            outline: 0;
            -webkit-appearance: none;
        }

        .glyphicon.glyphicon-comment{
            font-size: 25px;
        }
        a:link {
            text-decoration: none;
        }
        a:hover {
            text-decoration: none;
        }
        p{
            font-size: 14px;
            font-family: 'Slabo 27px', serif;
        }

        #idea{
            font-weight:bold;
        }
        .borderless td{
            color: #1c0000;
            border-top:1px solid #fff;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">


                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            Your profile
                            <div class="clearfix"></div>
                        </div>

                        <div class="panel-body">

                                <div class="modal-dialog modal-lg" role="document">

                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <div class="table-responsive">
                                                <table class="table borderless">
                                                    <tr>
                                                        <td colspan="2"> <img src="{{asset('uploads/users/'.$data->image)}}" alt="" width="200px"></td>
                                                    </tr>

                                                    <tr>
                                                        <td>
                                                            Name: {{$data->name}}
                                                        </td>
                                                        <td>Email: {{$data->email}}</td>
                                                    </tr>

                                                    <tr>
                                                        <td>Address: {{$data->address}}</td>
                                                        <td>Phone: {{$data->phone}}</td>
                                                    </tr>

                                                    <tr>
                                                        <td>Department: {{$data->student->department->name}}</td>
                                                        <td>Session: {{$data->student->session->name}}</td>
                                                    </tr>

                                                    <tr>
                                                        <td colspan="2">Batch: {{$data->student->batch->name}}</td>
                                                    </tr>

                                                </table>
                                            </div>
                                        </div>

                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog --
                        </div>
                    </div>


            </div>
        </div>
    </div>


@endsection