routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
})->middleware('guest');

Route::group(['middleware'=>'auth','role'=>['admin','qacoordinator','qualityassurancemanager']], function() {
    Route::resource('admin/', 'AdminHomeController');
    Route::resource('admin/posts', 'PostController');
});

Route::group(['middleware'=>'auth','role'=>['qualityassurancemanager']], function() {
    Route::resource('admin/tags', 'TagController');
});

Route::group(['middleware'=>'auth','role'=>['admin']], function(){
    Route::resource('admin/roles', 'RoleController');
    Route::resource('admin/departments', 'DepartmentController');
    Route::resource('admin/users', 'UserController');
    Route::resource('admin/session-departments', 'SessionDepartmentController');
    Route::resource('admin/batches', 'BatchController');
    Route::resource('admin/sections', 'SectionController');
});


Route::get('/getDeptWiseSession',['uses'=>'SessionDepartmentController@getDeptWiseSession','role'=>'admin','as'=>'getDeptWiseSession']);
Route::post('/getsessiondata',['uses'=>'SessionDepartmentController@getsessiondata','role'=>'qacoordinator','as'=>'getsessiondata']);
Route::post('/manageideapost',['uses'=>'SessionDepartmentController@manageideapost','role'=>'qacoordinator','as'=>'manageideapost']);
Route::post('/newPErmitForIdea',['uses'=>'SessionDepartmentController@newPErmitForIdea','role'=>'qacoordinator','as'=>'newPErmitForIdea']);
Route::post('/existingDate',['uses'=>'SessionDepartmentController@existingDate','role'=>'qacoordinator','as'=>'existingDate']);
Route::post('/disableIdeaControl',['uses'=>'SessionDepartmentController@disableIdeaControl','role'=>'qacoordinator','as'=>'disableIdeaControl']);
Route::get('/manageideapostPermission',['uses'=>'SessionDepartmentController@manageideapostPermission','role'=>'qacoordinator','as'=>'manageideapostPermission']);
Route::get('/getSessionWiseBatch',['uses'=>'BatchController@getSessionWiseBatch','role'=>'admin','as'=>'getSessionWiseBatch']);
Route::get('/allstudents',['uses'=>'Student\StudentController@allstudents','role'=>'admin','as'=>'allstudents']);
Route::get('/deptwiseallstudents',['uses'=>'Student\StudentController@deptwiseallstudents','role'=>'qacoordinator','as'=>'deptwiseallstudents']);
Route::get('/enable-post-idea',['uses'=>'Idea\IdeaController@enableidea','role'=>'qacoordinator','as'=>'enable-post-idea']);
Route::get('/alldocs',['uses'=>'Idea\IdeaController@alldocs','role'=>'qualityassurancemanager','as'=>'alldocs']);
Route::get('/approvenewidea',['uses'=>'Idea\IdeaController@approvenewidea','role'=>'qacoordinator','as'=>'approvenewidea']);
Route::get('/newidea',['uses'=>'Idea\IdeaController@newidea','role'=>'qacoordinator','as'=>'newidea']);
Route::post('/approve',['uses'=>'Idea\IdeaController@approve','role'=>'qacoordinator','as'=>'approve']);
Route::post('/deletePost',['uses'=>'Idea\IdeaController@deletePost','role'=>'qacoordinator','as'=>'deletePost']);
Route::post('/getuserinfo',['uses'=>'Idea\IdeaController@getuserinfo','role'=>'qacoordinator','as'=>'getuserinfo']);
Route::get('/allnewPosts',['uses'=>'Idea\IdeaController@allnewPosts','role'=>'qacoordinator','as'=>'allnewPosts']);
Route::get('/no_idea_comments',['uses'=>'Idea\IdeaController@no_idea_comments','role'=>['qacoordinator','qualityassurancemanager'],'as'=>'no_idea_comments']);
Route::get('/individualIdeaWithNoComment/{id}',['uses'=>'Idea\IdeaController@individualIdeaWithNoComment','role'=>['qacoordinator','qualityassurancemanager'],'as'=>'individualIdeaWithNoComment']);
Route::get('/annomynousIdeaAndComment',['uses'=>'Idea\IdeaController@annomynousIdeaAndComment','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'annomynousIdeaAndComment']);
Route::get('/categorywiseidea',['uses'=>'Idea\IdeaController@categorywiseidea','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'categorywiseidea']);
Route::post('/getallideaByTag',['uses'=>'Idea\IdeaController@getallideaByTag','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'getallideaByTag']);
Route::get('/chart',['uses'=>'AdminHomeController@chart','as'=>'chart','role'=>'admin']);
Route::get('/total_post_by_each_dept',['uses'=>'AdminHomeController@total_post_by_each_dept','as'=>'total_post_by_each_dept','role'=>['admin','qualityassurancemanager']]);



Auth::routes();
Route::get('/profile',['uses'=>'HomeController@profile','as'=>'profile','role'=>['student']]);

Route::get('/', ['uses'=>'HomeController@index','as'=>'home','role'=>['student']]);

Route::get('/post', ['uses'=>'HomeController@createPost','as'=>'createPost','role'=>['student']]);

Route::post('/post', ['uses'=>'HomeController@postIdea','as'=>'post','role'=>['student']]);

Route::get('/post/show/{id}', ['uses'=>'HomeController@postDetails','as'=>'post-details','role'=>['student']]);


Route::post('/comment', ['uses'=>'HomeController@postComment','as'=>'comment','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);

Route::post('/postLike', ['uses'=>'HomeController@postLike','as'=>'postLike','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);

Route::post('/postView', ['uses'=>'HomeController@postView','as'=>'postView','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);


Route::post('/getallFile',['uses'=>'Idea\IdeaController@getallFile','role'=>'qualityassurancemanager','as'=>'getallFile']);
Route::get('/myidea',['uses'=>'Idea\IdeaController@myidea','role'=>'student','as'=>'myidea']);
Route::post('/myidea',['uses'=>'Idea\IdeaController@deleteIdea','role'=>'student','as'=>'deleteIdea']);
Route::get('/myidea/{id}/edit',['uses'=>'Idea\IdeaController@editMyIdea','role'=>'student','as'=>'editmyidea']);
Route::post('/myidea/{post}',['uses'=>'Idea\IdeaController@updateIdea','role'=>'student','as'=>'updatemyidea']);

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users() {
    	return $this->hasMany('App\User');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role');
    }

    public function index()
    {
        $roles = Role::all();
        return view('admin.roles.index', compact(['roles']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $role = new Role;

        $this->validate($request,[
              'designation' => 'required|unique:roles|max:100',
              'salary' => 'required',
        ],[
              'designation.required' => ' The designation field is required.',
              'designation.max' => ' The designation may not be greater than 100 characters.',
              'designation.unique' => ' It seems designation already exist',
              'salary.required' => ' The salary field is required.',
        ]);

        $role->designation = $request->input('designation');
        $role->role_name = strtolower(str_replace(' ', '', $request->input('designation')));
        $role->salary = $request->input('salary');

       Session::flash('success','Role Successfully Added');

        $role->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('admin.roles.show', compact(['role']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('admin.roles.edit', compact(['role']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request,[
            'salary' => 'required',
            'designation' => 'required|max:100|unique:roles,designation,'.$role->id
              
        ],[
              'designation.required' => ' The designation field is required.',
              'designation.max' => ' The designation may not be greater than 100 characters.',
              'designation.unique' => ' It seems designation already exist',
              'salary.required' => ' The salary field is required.',
        ]);

         $role->designation = $request->input('designation');
         $role->salary = $request->input('salary');



        Session::flash('update','Role Successfully Update');

         $role->save();
         return redirect('admin/roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        Session::flash('delete','Role Successfully Delete');
        return redirect('admin/roles');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin')

@section('content')


	<div class="panel panel-primary panel-top">
	  <div class="panel-heading">
	    <span class="heading">Add New Role</span>
	     <a type="button" href="{{ route('roles.index') }}" class="btn btn-danger pull-right"> <i class="glyphicon glyphicon-remove"> </i> Cancel</a>
	      <div class="clearfix"></div>
	  </div>
	  <div class="panel-body">
      @if ($message = Session::get('success'))
      <div class="alert alert-success alert-block">
         <button type="button" class="close" data-dismiss="alert">×</button> 
              <strong>{{ $message }}</strong>
      </div>
      @endif
       @if(count($errors))
           <div class="alert alert-danger">
             <strong>Whoops!</strong> There were some problems with your input.
             <br/>
             <ul>
               @foreach($errors->all() as $error)
               <li>{{ $error }}</li>
               @endforeach
             </ul>
           </div>
         @endif
         
	        <form method="POST" action="{{ route('roles.store') }}">
	        {{ csrf_field() }}
            <label for="designation">Designation</label>
            <div class="form-group">
              <input type="text" name="designation" id="designation" class="form-control" placeholder="Enter Designation" required>
            </div>    
            <label for="salary">Salary</label>
            <div class="form-group">
              <input type="text" name="salary" id="salary" class="form-control" placeholder="Enter Salary" required>
            </div>          
            <br>
            <button type="submit" class="btn btn-primary"> <i class="glyphicon glyphicon-ok"> </i>  Save</button>
        </form>
	  </div>
	</div>
  
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin')

@section('content')


	<div class="panel panel-primary panel-top">    
	  <div class="panel-heading">
	    <span class="heading">Edit Role</span>
	     <a type="button" href="{{ route('roles.index') }}" class="btn btn-danger pull-right"> <i class="glyphicon glyphicon-remove"> </i> Cancel</a>
	      <div class="clearfix"></div>
	  </div>
	  <div class="panel-body">
      @if ($message = Session::get('update'))
      <div class="alert alert-success alert-block">
         <button type="button" class="close" data-dismiss="alert">×</button> 
              <strong>{{ $message }}</strong>
      </div>
      @endif

      @if(count($errors))
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.
            <br/>
            <ul>
              @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
        @endif

	        <form method="POST" action="{{ route('roles.update', ['role' => $role->id]) }}">
	          {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <label for="designation">Designation</label>
            <div class="form-group">
              <input type="text" name="designation" id="designation" class="form-control" placeholder="Enter Designation" value="{{ $role->designation }}" required>
            </div>
            <label for="salary">Salary</label>
            <div class="form-group">
              <input type="text" name="salary" id="salary" class="form-control" placeholder="Enter Salary" value="{{ $role->salary }}">
            </div>
            <br>
            <button type="submit" class="btn btn-primary m-t-15 waves-effect"> <i class="glyphicon glyphicon-ok"> </i>  Update</button>
        </form>
	  </div>
	</div>
  
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="panel panel-primary panel-top">
      <div class="panel-heading">
        <span class="heading">ROLE</span>
        <a type="button" href="{{route('roles.create')}}" class="btn btn-default pull-right hidden-print"> <i class="glyphicon glyphicon-plus"> </i> Add New Role</a>
        <button style="margin-right:5px;" title="Print" type="button" onclick="window.print();" class="btn btn-info pull-right hidden-print"><i class="glyphicon glyphicon-print"></i></button>
        <div class="clearfix"></div>
      </div>
      <div class="panel-body">
        @if ($message = Session::get('delete'))
        <div class="alert alert-danger alert-block">
           <button type="button" class="close" data-dismiss="alert">×</button> 
               <strong>{{ $message }}</strong>
        </div>
        @endif
        @if ($roles->count())
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th width="70%">Designation</th>
                    <th class="hidden-print">Action</th>
                </tr>
            </thead>
            @foreach($roles as $role)
            <tbody>
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $role->designation }}</td>
                    <td class="hidden-print">
                        <a type="button" href="{{ route('roles.show', ['role' => $role->id]) }}" class="btn btn-success glyphicon glyphicon-eye-open" title="Show"></a>
                        <a type="button" href="{{ route('roles.edit', ['role' => $role->id]) }}" class="btn btn-warning glyphicon glyphicon-edit" title="Edit"></a>
                        <form action="{!! action('RoleController@destroy', $role->id) !!}" method="POST" style="display: inline-block;">
                            {{ csrf_field() }} {{ method_field('DELETE') }}
                           <button type="submit" title="Delete" role="button" class="btn btn-danger"><i class="glyphicon glyphicon-trash" title="Delete"></i></button>
                        </form>        
                    </td>
                </tr>
            </tbody>
            @endforeach
        </table>
        @endif
      </div>
    </div>

@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="panel panel-primary panel-top">
      <div class="panel-heading">
        <span class="heading">ROLE DETAILS</span>
        <a type="button" href="{{route('roles.index')}}" class="btn btn-default pull-right hidden-print"> <i class="glyphicon glyphicon-menu-left"> </i> Go To Index</a>
        <button style="margin-right:5px;" title="Print" type="button" onclick="window.print();" class="btn btn-info pull-right hidden-print"><i class="glyphicon glyphicon-print"></i></button>
        <div class="clearfix"></div>
      </div>
      <div class="panel-body">
        <p><label>Designation:</label> {{ $role->designation }}</p>
        <p><label>Salary:</label> {{ $role->salary }}</p>
 
        <div class="row">
            <div class="col-lg-12 text-right hidden-print">
                  <a type="button" href="{{ route('roles.edit', ['role' => $role->id]) }}" class="btn btn-success glyphicon glyphicon-edit" title="Edit"></a>
                <form action="{!! action('RoleController@destroy', $role->id) !!}" method="POST" style="display: inline-block;">
                    {{ csrf_field() }} {{ method_field('DELETE') }}
                   <button type="submit" title="Delete" role="button" class="btn btn-danger"><i class="glyphicon glyphicon-trash" title="Delete"></i></button>
                </form>        
            </div>
        </div>
      </div>
    </div>
    
@endsection