routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
})->middleware('guest');

Route::group(['middleware'=>'auth','role'=>['admin','qacoordinator','qualityassurancemanager']], function() {
    Route::resource('admin/', 'AdminHomeController');
    Route::resource('admin/posts', 'PostController');
});

Route::group(['middleware'=>'auth','role'=>['qualityassurancemanager']], function() {
    Route::resource('admin/tags', 'TagController');
});

Route::group(['middleware'=>'auth','role'=>['admin']], function(){
    Route::resource('admin/roles', 'RoleController');
    Route::resource('admin/departments', 'DepartmentController');
    Route::resource('admin/users', 'UserController');
    Route::resource('admin/session-departments', 'SessionDepartmentController');
    Route::resource('admin/batches', 'BatchController');
    Route::resource('admin/sections', 'SectionController');
});


Route::get('/getDeptWiseSession',['uses'=>'SessionDepartmentController@getDeptWiseSession','role'=>'admin','as'=>'getDeptWiseSession']);
Route::post('/getsessiondata',['uses'=>'SessionDepartmentController@getsessiondata','role'=>'qacoordinator','as'=>'getsessiondata']);
Route::post('/manageideapost',['uses'=>'SessionDepartmentController@manageideapost','role'=>'qacoordinator','as'=>'manageideapost']);
Route::post('/newPErmitForIdea',['uses'=>'SessionDepartmentController@newPErmitForIdea','role'=>'qacoordinator','as'=>'newPErmitForIdea']);
Route::post('/existingDate',['uses'=>'SessionDepartmentController@existingDate','role'=>'qacoordinator','as'=>'existingDate']);
Route::post('/disableIdeaControl',['uses'=>'SessionDepartmentController@disableIdeaControl','role'=>'qacoordinator','as'=>'disableIdeaControl']);
Route::get('/manageideapostPermission',['uses'=>'SessionDepartmentController@manageideapostPermission','role'=>'qacoordinator','as'=>'manageideapostPermission']);
Route::get('/getSessionWiseBatch',['uses'=>'BatchController@getSessionWiseBatch','role'=>'admin','as'=>'getSessionWiseBatch']);
Route::get('/allstudents',['uses'=>'Student\StudentController@allstudents','role'=>'admin','as'=>'allstudents']);
Route::get('/deptwiseallstudents',['uses'=>'Student\StudentController@deptwiseallstudents','role'=>'qacoordinator','as'=>'deptwiseallstudents']);
Route::get('/enable-post-idea',['uses'=>'Idea\IdeaController@enableidea','role'=>'qacoordinator','as'=>'enable-post-idea']);
Route::get('/alldocs',['uses'=>'Idea\IdeaController@alldocs','role'=>'qualityassurancemanager','as'=>'alldocs']);
Route::get('/approvenewidea',['uses'=>'Idea\IdeaController@approvenewidea','role'=>'qacoordinator','as'=>'approvenewidea']);
Route::get('/newidea',['uses'=>'Idea\IdeaController@newidea','role'=>'qacoordinator','as'=>'newidea']);
Route::post('/approve',['uses'=>'Idea\IdeaController@approve','role'=>'qacoordinator','as'=>'approve']);
Route::post('/deletePost',['uses'=>'Idea\IdeaController@deletePost','role'=>'qacoordinator','as'=>'deletePost']);
Route::post('/getuserinfo',['uses'=>'Idea\IdeaController@getuserinfo','role'=>'qacoordinator','as'=>'getuserinfo']);
Route::get('/allnewPosts',['uses'=>'Idea\IdeaController@allnewPosts','role'=>'qacoordinator','as'=>'allnewPosts']);
Route::get('/no_idea_comments',['uses'=>'Idea\IdeaController@no_idea_comments','role'=>['qacoordinator','qualityassurancemanager'],'as'=>'no_idea_comments']);
Route::get('/individualIdeaWithNoComment/{id}',['uses'=>'Idea\IdeaController@individualIdeaWithNoComment','role'=>['qacoordinator','qualityassurancemanager'],'as'=>'individualIdeaWithNoComment']);
Route::get('/annomynousIdeaAndComment',['uses'=>'Idea\IdeaController@annomynousIdeaAndComment','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'annomynousIdeaAndComment']);
Route::get('/categorywiseidea',['uses'=>'Idea\IdeaController@categorywiseidea','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'categorywiseidea']);
Route::post('/getallideaByTag',['uses'=>'Idea\IdeaController@getallideaByTag','role'=>['admin','qacoordinator','qualityassurancemanager'],'as'=>'getallideaByTag']);
Route::get('/chart',['uses'=>'AdminHomeController@chart','as'=>'chart','role'=>'admin']);
Route::get('/total_post_by_each_dept',['uses'=>'AdminHomeController@total_post_by_each_dept','as'=>'total_post_by_each_dept','role'=>['admin','qualityassurancemanager']]);



Auth::routes();
Route::get('/profile',['uses'=>'HomeController@profile','as'=>'profile','role'=>['student']]);

Route::get('/', ['uses'=>'HomeController@index','as'=>'home','role'=>['student']]);

Route::get('/post', ['uses'=>'HomeController@createPost','as'=>'createPost','role'=>['student']]);

Route::post('/post', ['uses'=>'HomeController@postIdea','as'=>'post','role'=>['student']]);

Route::get('/post/show/{id}', ['uses'=>'HomeController@postDetails','as'=>'post-details','role'=>['student']]);


Route::post('/comment', ['uses'=>'HomeController@postComment','as'=>'comment','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);

Route::post('/postLike', ['uses'=>'HomeController@postLike','as'=>'postLike','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);

Route::post('/postView', ['uses'=>'HomeController@postView','as'=>'postView','role'=>['student','qacoordinator','qualityassurancemanager','admin']]);


Route::post('/getallFile',['uses'=>'Idea\IdeaController@getallFile','role'=>'qualityassurancemanager','as'=>'getallFile']);
Route::get('/myidea',['uses'=>'Idea\IdeaController@myidea','role'=>'student','as'=>'myidea']);
Route::post('/myidea',['uses'=>'Idea\IdeaController@deleteIdea','role'=>'student','as'=>'deleteIdea']);
Route::get('/myidea/{id}/edit',['uses'=>'Idea\IdeaController@editMyIdea','role'=>'student','as'=>'editmyidea']);
Route::post('/myidea/{post}',['uses'=>'Idea\IdeaController@updateIdea','role'=>'student','as'=>'updatemyidea']);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>e-Idea</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ asset('css/sb-admin.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    @yield('css')



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{route('index')}}">e-Idea</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                @if(\Illuminate\Support\Facades\Auth::user()->hasRole('qacoordinator'))
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" ><i class="fa fa-bell"></i> <span id="totalnewidea"  class="badge" style="color: red;"></span> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown" id="newideas">
                    </ul>
                </li>
                @endif
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ Auth::user()->name }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">

                        <li>
                            <a href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                               document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
						
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="{{url('admin/')}}"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
                    </li>
                    @if(\Illuminate\Support\Facades\Auth::user()->hasRole('admin'))
                    <li>
                        <a href="{{ route('posts.index') }}"><i class="fa fa-lightbulb-o" style="color: #ff5100;"></i> View all ideas</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-sliders" aria-hidden="true"></i> Manage <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            {{--<li>--}}
                                {{--<a href="{{ route('roles.index') }}"><i class="far fa-life-ring"></i> Manage Role</a>--}}
                            {{--</li>--}}
                            <li>
                                <a href="{{ route('departments.index') }}"><i class="fa fa-building" aria-hidden="true"></i> Manage Departments</a>
                            </li>
                            <li>
                                <a href="{{ route('session-departments.index') }}"><i class="fa fa-clock-o" aria-hidden="true"></i> Manage Sessions</a>
                            </li>
                            <li>
                                <a href="{{ route('batches.index') }}"><i class="fa fa-id-badge" aria-hidden="true"></i> Manage Batch</a>
                            </li>
                            {{--<li>--}}
                                {{--<a href="{{ route('sections.index') }}"><i class="fa fa-fw fa-desktop"></i> Manage Section</a>--}}
                            {{--</li>--}}
                        </ul>
                    </li>
                        <li>
                            <a href="{{ route('users.index') }}"><i class="fa fa-users" aria-hidden="true"></i> Manage Users</a>
                        </li>
                    <li>
                        <a href="{{route('allstudents')}}"><i class="fa fa-graduation-cap" aria-hidden="true"></i>  All students</a>
                    </li>
                    @elseif(\Illuminate\Support\Facades\Auth::user()->hasRole('qacoordinator'))
                    <li>
                        <a href="{{ route('posts.index') }}"><i  class="fa fa-lightbulb-o" style="color: #ff5100;"></i> View all ideas</a>
                    </li>
                    <li>
                        <a href="{{route('approvenewidea')}}"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Approve new ideas</a>
                    </li>
                    <li>
                        <a href="{{route('manageideapostPermission')}}"><i class="fa fa-cog" aria-hidden="true"></i> Manage idea post</a>
                    </li>
                    <li>
                        <a href="{{route('categorywiseidea')}}"><i class="fa fa-stack-exchange" aria-hidden="true"></i> Idea category</a>
                    </li>
                    <li>
                        <a href="{{route('deptwiseallstudents')}}"><i class="fa fa-address-card"></i> All students</a>
                    </li>

                    {{--<li>--}}
                        {{--<a href="{{route('enable-post-idea')}}"><i class="fas fa-check"></i> Permit to post Idea</a>--}}
                    {{--</li>--}}

                    <li>
                        <a href="{{route('annomynousIdeaAndComment')}}"><i class="fa fa-user-secret"></i> Anonymous ideas and comments</a>
                    </li>

                    @elseif(\Illuminate\Support\Facades\Auth::user()->hasRole('qualityassurancemanager'))

                    <li>
                        <a href="{{ route('posts.index') }}"><i class="fa fa-lightbulb-o" style="color: #ff5100;"></i> View all ideas</a>
                    </li>
                    <li>
                        <a href="{{route('no_idea_comments')}}"><i class="fa fa-user-secret" aria-hidden="true"></i> Ideas without any comments</a>
                    </li>

                    <li>
                        <a href="{{ route('tags.index') }}"><i class="fa fa-fw fa-edit"></i> Manage Tags</a>
                    </li>

                    <li>
                        <a href="{{ route('alldocs') }}"><i class="fa fa-file-text-o" aria-hidden="true"></i> All docs</a>
                    </li>
                    {{--<li>--}}
                        {{--<a href="{{ route('posts.index') }}"><i class="fa fa-lightbulb-o" aria-hidden="true"></i> View all ideas</a>--}}
                    {{--</li>--}}
                    @endif
                </ul>
            </div>

            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        @yield('content')
                    </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{{ asset('js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
{{--    <script src="{{ asset('js/fontawesome-all.min.js') }}"></script>--}}
    {{--<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>--}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    
    @yield('script')
    <script>
        var arrayofID=[];
        $(document).ready(function () {

            $.ajax({
                url:'{{route('allnewPosts')}}',
                type:'get',
                success:function (data) {

                    $('#totalnewidea').text(data.length);
                    var list='';
                    for(var i=0;i<data.length;i++)
                    {
                        arrayofID.push(data[i].id);
                        list+='<li><a href="#"> <span class="glyphicon glyphicon-pencil" ></span> '+data[i].body+' by '+data[i].user.name+'</a></li>';
                    }
                    list+='<li><a href="{{route('approvenewidea')}}"><span class="glyphicon glyphicon-th"></span> View All</a> </li>';
                    $('#newideas').html(list);
                }
            })


            console.log(arrayofID);
        })
    </script>

</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Styles -->
    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @yield('style')

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}" style="color: #fff">
                        {{ config('app.name') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">

                    @guest

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('login') }}">Login</a></li>
                    </ul>

                    @else

                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>


                    </ul>
                        <ul class="nav navbar-nav">
                            <li><a href="{{route('myidea')}}"><i class="fa fa-lightbulb-o" aria-hidden="true"></i> My ideas</a></li>
                            <li><a href="{{route('profile')}}"><i class="fa fa-address-card-o" aria-hidden="true"></i> My Profile</a></li>
                        </ul>
                    @endguest

                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <script>

        $('.alert').delay(5000).fadeOut(1000,function () {
            $(this).alert('close');
        });
    </script>

    @yield('script')


</body>
</html>